int A = new Random().Next(2,10);
Console.WriteLine(A);
int B = new Random().Next(2,10);
Console.WriteLine(B);
int result = A + B;
// Console.WriteLine("Введите первое слагаемое: ");
// int A = Console.ReadLine();
// Console.Write("A = " + A);
// Console.WriteLine("Введите второе слагаемое: ");
// int B = Console.ReadLine();
Console.WriteLine(result);